CREATE TABLE [dbo].[Address]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[Country] NVARCHAR(256) NOT NULL,
	[City] NVARCHAR(256) NOT NULL,
	[ZIP] NVARCHAR(64) NOT NULL,
	[Street] VARCHAR(256) NOT NULL,
	[CompanyId] INT NOT NULL FOREIGN KEY REFERENCES Company(Id),
	[CreationTime] DATETIME NOT NULL DEFAULT getDate(),
	[DeletionTime] DATETIME,
)
